'''
 ASTgen from JSON
 Author: @hithja
'''
import sys
from pathlib import Path
import json

code = ""

def main():
    if len(sys.argv) != 3:
        print(f"Usage: python3 {sys.argv[0]} <config> <dir>")
        sys.exit(64)
    
    ast = {}
    with open(sys.argv[1], "r") as f:
        ast = json.load(f)

    defineAst(sys.argv[2], ast)

def defineAst(dir: str, ast: dict):
    global code

    out_dir = Path(dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    path = dir + "/" + ast["name"] + ".hpp"

    code = f"/*\n\t- Generated by ASTgen\n\t- GenAst.py usage: python3 {sys.argv[0]} {dir}\n*/\n#pragma once\n"

    for lib in ast["sys_includes"]:
        code += f"#include <{lib}>\n"

    for lib in ast["user_includes"]:
        code += f"#include \"{lib}\"\n"

    code += f"""
using Object = std::variant<std::string, std::monostate, double, bool>; 
                
class {ast["name"]} {{
    public:

}};
    """

    for cName, field in ast["types"].items():
        code += defineType(ast["name"], cName, field)

    with open(path, "w", encoding="utf-8") as f:
        f.write(code)

    print("AST successfully generated!")

def defineType(name: str, className: str, field: str):
    code_str = ""

    fields = []
    for i in field.split(","):
        type_name, var_name = i.strip().split()
        type_name = check_type(name, type_name)
        fields.append((type_name, var_name))

    code_str += f"""
class {className} : public {name} {{
    public:
"""
    for i in fields:
        code_str += f"\t{i[0]} {i[1]};\n"

    # Constructor
    code_str += f"\n\t{className}("
    for i in range(len(fields)):
        if i != len(fields)-1:
            code_str += f"{fields[i][0]} {fields[i][1]}, "
        else:
            code_str += f"{fields[i][0]} {fields[i][1]}"

    code_str += ")"
    for i in range(len(fields)):
        if i == 0:
            if i != len(fields)-1:
                code_str += f"\n\t: {fields[i][1]}({fields[i][1]}),\n"
            else:
                code_str += f"\n\t: {fields[i][1]}({fields[i][1]}) {{}}\n"
        else:
            if i != len(fields)-1:
                code_str += f"\t{fields[i][1]}({fields[i][1]}),\n"
            else:
                code_str += f"\t{fields[i][1]}({fields[i][1]}) {{}}\n"
    
    code_str += "};\n"

    return code_str

def check_type(baseClass: str, type: str):
    if type == baseClass:
        return f"std::shared_ptr<{baseClass}>"
    return type

if __name__ == '__main__':
    main()